### PR TITLE
Add support for bulk-data and sql-query endpoints

### LINKED ISSUE #30: Implement bulk-data endpoint

### PR DESCRIPTION
**Pull request by pshapiro4broad**
Fixes #30, #31 

The code works, as tested locally. I'm looking at adding automated tests, but the code is ready to merge.

### CODE REVIEW

**Comment by kaushik-work** [comment]
This is not a big thing but: As it stands now, if I take the SQL generated by the translator (and returned with my query result) and feed it into the bare SQL endpoint will it work? I forget what we do with limit and offset. Will this appear twice in such a case? Will the SQL be valid? Thanks!

**Comment by pshapiro4broad** [comment]
> This is not a big thing but: As it stands now, if I take the SQL generated by the translator (and returned with my query result) and feed it into the bare SQL endpoint will it work? I forget what we do with limit and offset. Will this appear twice in such a case? Will the SQL be valid? Thanks!

Right now the returned SQL doesn't include limit and offset. It would be easy to change this.

I've been thinking that in the future we will probably want to use bigquery to do pagination, and only support forward pagination (by using `nextUrl` in the response). In that case the SQL wouldn't include the pagination information. But for now since we are doing it in SQL, adding limit and offset makes sense.

**Comment by pshapiro4broad** [comment]
Including limit and offset will make it a little odd in that the `sql-query` endpoint also accepts limit and offset as arguments. Right now we always add them to the query, so you'd have to remove them before calling this endpoint with the returned SQL (if they were included in the returned SQL).

**Comment by kaushik-work** [comment]
Ok, I think this is fine as it is 

1. The translator generates the bare SQL without limit and offset
2. All endpoints use limit and offset as separate parameters
3. The returned results contain the limit and offset for reproducibility

Documentation in the bare SQL endpoint that brings attention to the fact that limit and offset are added in separately will be good.

**Comment by pshapiro4broad** [comment]
> The returned results contain the limit and offset for reproducibility

Currently the query result doesn't include `limit` and `offset`. But the API caller would know them.

> Documentation in the bare SQL endpoint that brings attention to the fact that limit and offset are added in separately will be good.

I agree 👍

**Review by kaushik-work — APPROVED** [review]
Thank you @pshapiro4broad

**Pull request merged**
